# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-14 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rows',
            old_name='seat_id',
            new_name='row_id',
        ),
        migrations.AddField(
            model_name='seat',
            name='aisle',
            field=models.BooleanField(default=False),
        ),
    ]
