# Generated by Django 2.0.2 on 2018-02-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20180221_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querycnt',
            name='query',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
