# Generated by Django 2.0.2 on 2018-02-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20180221_0737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analytics',
            new_name='AnalyticCount',
        ),
    ]
