# Generated by Django 2.0.2 on 2018-02-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20180221_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entitygroup',
            name='is_loop',
            field=models.BooleanField(default=False),
        ),
    ]
