# Generated by Django 2.0.2 on 2018-02-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20180222_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('user_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'debug - Feedback',
                'verbose_name_plural': 'debug - Feedbacks',
            },
        ),
        migrations.AddField(
            model_name='entitygroup',
            name='is_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitygroup',
            name='is_dropdown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitygroup',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entitygroup',
            name='multi',
            field=models.BooleanField(default=False),
        ),
    ]
