# Generated by Django 2.0.2 on 2018-02-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_auto_20180222_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='current_stage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionsentitygroup',
            name='entity_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_group_set', to='engine.EntityGroup'),
        ),
    ]
