# Generated by Django 2.0.2 on 2018-02-23 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_auto_20180223_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='count',
            new_name='cnt',
        ),
    ]
