# Generated by Django 2.0.2 on 2018-02-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0011_auto_20180223_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='current_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
    ]
