# Generated by Django 2.0.2 on 2018-02-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0012_auto_20180223_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsentitygroup',
            name='entity_to_delete',
            field=models.TextField(blank=True, help_text='Please enter different entities seperated by space which are to be deleted', null=True),
        ),
        migrations.AddField(
            model_name='questionsentitygroup',
            name='intent_on_click',
            field=models.TextField(blank=True, null=True),
        ),
    ]
