# Generated by Django 2.0.2 on 2018-02-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0013_auto_20180226_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='redirect_entities_delete',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='redirect_intent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
